name: crypto_currency

services:
  app:
    build: images/application
    container_name: symfony_app
    depends_on:
      - mongo
    init: true
    volumes:
      - ./application:/var/www/html
      - ./images/application/usr/local/etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./images/application/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./data/share:/usr/share/data
    working_dir: /var/www/html
    networks:
      - symfony_network
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    extra_hosts:
      host.docker.internal: host-gateway

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www/html
      - ./images/application/nginx/config/http-application.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony_network

  mongo:
    image: mongo:4.4
    container_name: symfony_mongo
    ports:
      - "${MONGO_SERVER_PORT}:27017"
    environment:
      - MONGODB_INITDB_DATABASE=${MONGODB_DB:-app}
    volumes:
      - ./data/mongo:/data/db:delegated
      - ./data/share:/usr/share/data
    networks:
      - symfony_network

networks:
  symfony_network: