name: boilerplate-test

services:
  app:
    build: images/application
    container_name: boilerplate_app
    depends_on:
      - mongo
      - mysql
    init: true
    volumes:
      - ./application:/var/www/html
      - ./images/application/usr/local/etc/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./images/application/usr/local/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./images/application/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./data/share:/usr/share/data
    working_dir: /var/www/html
    networks:
      - boilerplate_network
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    extra_hosts:
      host.docker.internal: host-gateway

  nginx:
    image: nginx:latest
    container_name: boilerplate_nginx
    ports:
      - "80:80"
    volumes:
      - ./application:/var/www/html
      - ./images/application/nginx/config/http-application.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - boilerplate_network

  mongo:
    image: mongo:4.4
    container_name: boilerplate_mongo
    ports:
      - "${MONGO_SERVER_PORT}:27017"
    environment:
      - MONGODB_INITDB_DATABASE=${MONGODB_DB:-app}
    volumes:
      - ./data/mongo:/data/db:delegated
      - ./data/share:/usr/share/data
    networks:
      - boilerplate_network

  mysql:
    image: mysql:8.1
    container_name: boilerplate_mysql
    ports:
      - 3306:3306
    volumes:
      - ./data/db/data:/var/lib/mysql
      - ./data/logs:/var/log/mysql
      - ./data/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate
      MYSQL_USER: boilerplate
      MYSQL_PASSWORD: boilerplate
    networks:
      - boilerplate_network

  mail:
    image: axllent/mailpit:latest
    container_name: boilerplate_mail
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - boilerplate_network

networks:
  boilerplate_network: